### ISSUE TITLE
is it possible to support element match expressions for mongo

### ISSUE THREAD

**Issue by berlinguyinca** [RutledgePaulV/q-builders#6]
hi,

would it be possible to support element match?

like described here?

https://docs.mongodb.org/manual/reference/operator/query/elemMatch/

we plan on utilizing the rest query project

https://github.com/rutledgepaulv/rest-query-engine

thank you very much

**Comment by RutledgePaulV** [comment]
One, thanks for the heads up on your plans to use rest-query-engine. I'll see if I can finish cleaning it up with tests and get a version 1.0 released to central this weekend. 

Two, yes $elemMatch functionally is already already implemented using what I'm calling a "ConditionProperty" query field type. Please let me know if you need any more guidance than below. I'm happy to create documentation as needed. 


```java
public class Person {
    private List<Person> friends = new ArrayList<>();
    private int age;
    private int name;
}


public class PersonQuery extends QBuilder<PersonQuery> {

     public ConditionProperty<PersonQuery, PersonQuery> friends() {
         return condition("friends");
     }

    public IntegerProperty<PersonQuery> age() {
        return intNum("age");
    }

    public StringProperty<PersonQuery> name() {
        return string("name");
    }

}


Condition<PersonQuery> elemMatch = new PersonQuery().name().eq("Joe").and().age().eq(30);
Condition<PersonQuery> query = new PersonQuery().friends().any(elemMatch);
Criteria criteria = query.query(new MongoVisitor());

List<Person> personsWithAtLeastOneFriendNamedJoeWhoIs30YearsOld = mongoTemplate.find(Query.query(criteria));

```

**Comment by berlinguyinca** [comment]
thanks this looks great, do you by any chance also have an example how to
write this as a RSQL string?

we are really excited about this tool, since it will save us a lot of time
to write our own implementations.

g.

On Sat, Mar 5, 2016 at 12:48 AM, Paul Rutledge <notifications@github.com>
wrote:

> One, thanks for the heads up on your plans to use rest-query-engine. I'll
> see if I can finish cleaning it up with tests and get a version 1.0
> released to central this weekend.
>
> Two, yes $elemMatch functionally is already already implemented using what
> I'm calling a "ConditionProperty" query field type. Please let me know if
> you need any more guidance than below. I'm happy to create documentation as
> needed.
>
> public class Person {
>     private List<Person> friends = new ArrayList<>();
>     private int age;
>     private int name;
> }
>
> public class PersonQuery extends QBuilder<PersonQuery> {
>
>      public ConditionProperty<PersonQuery, PersonQuery> friends() {
>          return condition("friends");
>      }
>
>     public IntegerProperty<PersonQuery> age() {
>         return intNum("age");
>     }
>
>     public StringProperty<PersonQuery> name() {
>         return string("name");
>     }
>
> }
>
> Condition<PersonQuery> elemMatch = new PersonQuery().name().eq("Joe").and().age().eq(30);Condition<PersonQuery> query = new PersonQuery().friends().any(elemMatch);Criteria criteria = query.query(new MongoVisitor());
> List<Person> personsWithAtLeastOneFriendNamedJoeWhoIs30YearsOld = mongoTemplate.find(Query.query(criteria));
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RutledgePaulV/q-builders/issues/6#issuecomment-192608702>
> .
>



-- 
------------------------------------------------------------
Lead Developer - Fiehnlab, UC Davis

gert wohlgemuth

work:
http://fiehnlab.ucdavis.edu/staff/wohlgemuth

phone:
530 665 9477

coding blog:
http://codingandmore.blogspot.com

linkedin:
http://www.linkedin.com/profile/view?id=28611299&trk=tab_pro

**Comment by RutledgePaulV** [comment]
Yes, you can see the rsql in the second snippet above

```java
public void show() {

        String incomingRsql = "friends=q='name==\"Joe\";age==\"30\"'";
        Condition<GeneralQueryBuilder> condition = pipeline.apply(incomingRsql, Person.class);
        Criteria mongodb = condition.query(new MongoVisitor());
        System.out.println(mongodb.getCriteriaObject().toString());
        // { "friends" : { "$elemMatch" : { "$and" : [ { "name" : "Joe"} , { "age" : 30}]}}}

}
```

Notice that the operator I'm using is "=q=". The value of the expression is just another RSQL query (with the keys targeted as if the root object is now the type of object in the multi-value field.

Perhaps another example without "Person" for both would help...

```java
public class Farm {
    private String state;
    private List<Animal> animals = new LinkedList<>();
}

public class Animal {
    private String name;
    private int age;   
}

public class FarmQuery extends QBuilder<FarmQuery> {
    public ConditionProperty<FarmQuery, AnimalQuery> animals() {
            return condition("animals");
    }
   
    public StringProperty<FarmQuery> state() {
            return string("state");
    }
}

public class AnimalQuery extends QBuilder<AnimalQuery> {

        public IntegerProperty<AnimalQuery> age() {
            return intNum("age");
        }

        public StringProperty<AnimalQuery> name() {
            return string("name");
        }

}
```


The RSQL would be:

```sql
state=='California';animals=q='name=="Charlotte";age==1'
```

The query builder form would be:
```java
Condition<FarmQuery> query = new FarmQuery().state().eq("California").and().animals().any(new AnimalQuery().name().eq("Charlotte").and().age().eq(1));
```


The mongo form would be:
```javascript
{  "$and": [{ "state" : "California" }, { "animals" : { "$elemMatch" : { "$and" : [ { "name" : "Charlotte"} , { "age" : 1}]}}}]}
```

**Comment by RutledgePaulV** [comment]
Unrelated, I saw you forked rest-query-engine - just a heads up that there was a bug in it that would prevent parsing subqueries due to something in q-builders. I released q-builders 1.1 to fix it and have updated the source for rest-query-engine.

**Comment by berlinguyinca** [comment]
thanks sounds good, let me play a bit with it. Thanks again for your quick
respomse

g.

On Sat, Mar 5, 2016 at 12:27 PM, Paul Rutledge <notifications@github.com>
wrote:

> Unrelated, I saw you forked rest-query-engine - just a heads up that there
> was a bug in it that would prevent parsing subqueries due to something in
> q-builders. I released q-builders 1.1 to fix it and have updated the source
> for rest-query-engine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RutledgePaulV/q-builders/issues/6#issuecomment-192729257>
> .
>



-- 
------------------------------------------------------------
Lead Developer - Fiehnlab, UC Davis

gert wohlgemuth

work:
http://fiehnlab.ucdavis.edu/staff/wohlgemuth

phone:
530 665 9477

coding blog:
http://codingandmore.blogspot.com

linkedin:
http://www.linkedin.com/profile/view?id=28611299&trk=tab_pro

**Comment by RutledgePaulV** [comment]
No problem. I'm going to close this ticket for now as I think you'll find your original concern is indeed already implemented. If you need any help getting started with things feel free to ask in the gitter room and I'll get back to you before long :)

https://gitter.im/RutledgePaulV/q-builders

**Comment by berlinguyinca** [comment]
Thank you,

our tests are working now, after we downloaded the two projects and build
them locally. Do you have an estimate when they both will be in the
repository? Also we discovered that the pom needs to be updated in the
rest-query-engine to pull in the correct snapshot of q-builder.

thanks again

g.


On Sat, Mar 5, 2016 at 1:12 PM, Paul Rutledge <notifications@github.com>
wrote:

> No problem. I'm going to close this ticket for now as I think you'll find
> your original concern is indeed already implemented. If you need any help
> getting started with things feel free to ask in the gitter room and I'll
> get back to you before long :)
>
> https://gitter.im/RutledgePaulV/q-builders
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RutledgePaulV/q-builders/issues/6#issuecomment-192738879>
> .
>



-- 
------------------------------------------------------------
Lead Developer - Fiehnlab, UC Davis

gert wohlgemuth

work:
http://fiehnlab.ucdavis.edu/staff/wohlgemuth

phone:
530 665 9477

coding blog:
http://codingandmore.blogspot.com

linkedin:
http://www.linkedin.com/profile/view?id=28611299&trk=tab_pro
